name: Publish crate

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: publish crates
      uses: katyo/publish-crates@v1
      with:
        # Github API token
        #token: # optional, default is ${{ github.token }}
        # Path to Rust crate or workspace
        #path: # optional, default is .
        # Extra arguments for cargo publish
        #args: # optional, default is
        # Cargo registry token
        #registry-token: # optional, default is
        # Skip execution cargo publish
        #dry-run: # optional, default is false
        # Check repository consistency
        #check-repo: # optional, default is true
        # Extra post publish delay (milliseconds)
        #publish-delay: # optional, default is 0
        # Disable cargo publish validation and cyclic dependency checks
        #no-verify: # optional, default is false
        # Exit the workflow gracefully if package does not have a new version to publish
        ignore-unpublished-changes: true
